erDiagram
    CLIENTE ||--o{ RESERVA : realiza
    PISTA ||--o{ RESERVA : "es reservada"

    CLIENTE {
        int id_cliente PK
        string nombre
        string direccion
        string telefono
        string email
    }

    PISTA {
        int id_pista PK
        int capacidad_sugerida
    }

    RESERVA {
        int id_reserva PK
        int id_cliente FK
        int id_pista FK
        date fecha_reserva
        time hora_inicio_prevista
        time hora_fin_prevista
        int cantidad_jugadores_registrados
        string estado
    }
