classDiagram
    class Cliente {
        +int idCliente
        +string nombre
        +string email
        +string telefono
        +registrarReserva()
    }

    class Pista {
        +int idPista
        +int capacidadMaxima
        +isDisponible(fecha, hora) bool
    }

    class TarifaPista {
        +int idTarifaPista
        +string diaSemana
        +Time horaInicioValidez
        +Time horaFinValidez
        +Date fechaInicioVigencia
        +Date fechaFinVigencia
        +decimal precioBase
    }

    class Reserva {
        +int idReserva
        +Date fechaTurno
        +DateTime inicioPrevisto
        +DateTime finPrevisto
        +int cantidadJugadores
        +string estado
        +decimal costoTotalCalculado
        +checkIn()
        +finalizar()
        +cancelar()
    }

    Cliente "1" -- "*" Reserva : realiza
    Pista "1" -- "*" Reserva : se reserva en
    Pista "1" -- "*" TarifaPista : tiene
    TarifaPista "1" -- "*" Reserva : se aplica en
